<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_My Reviews(1) Record FoundJob TitleSub _95f99d</name>
   <tag></tag>
   <elementGuidId>038d2f15-0a5d-4c38-b461-037b53cb8701</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.orangehrm-background-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1bbfdcd5-bb6c-4664-94f0-19f80c37e9fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>orangehrm-background-container</value>
      <webElementGuid>700db91f-cd73-4ff9-a91a-0f618fc1688c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>My Reviews(1) Record FoundJob TitleSub UnitReview PeriodAscendingDescendingDue DateAscendingDescendingSelf Evaluation StatusAscendingDescendingReview StatusAscendingDescendingActionsHR ManagerHuman ResourcesReview Period2022-07-01 - 2022-12-302022-12-31ActivatedActivated</value>
      <webElementGuid>9c5a8213-1790-4b56-98f1-654a03994abf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;oxd-layout&quot;]/div[@class=&quot;oxd-layout-container&quot;]/div[@class=&quot;oxd-layout-context&quot;]/div[@class=&quot;orangehrm-background-container&quot;]</value>
      <webElementGuid>4ea27230-d5be-42ad-9811-a79ef94b7ebe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[2]/div</value>
      <webElementGuid>bd0904e4-e78c-4f26-9c51-1ac09e1f1ffe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage Reviews'])[1]/following::div[5]</value>
      <webElementGuid>5b1512ba-d66a-4ea6-b06d-98894d0cd10a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Configure'])[1]/following::div[5]</value>
      <webElementGuid>6be165ef-203f-4664-9162-16dce801892c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div</value>
      <webElementGuid>715fd690-d0ac-4522-b173-a3eb8ad08bbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'My Reviews(1) Record FoundJob TitleSub UnitReview PeriodAscendingDescendingDue DateAscendingDescendingSelf Evaluation StatusAscendingDescendingReview StatusAscendingDescendingActionsHR ManagerHuman ResourcesReview Period2022-07-01 - 2022-12-302022-12-31ActivatedActivated' or . = 'My Reviews(1) Record FoundJob TitleSub UnitReview PeriodAscendingDescendingDue DateAscendingDescendingSelf Evaluation StatusAscendingDescendingReview StatusAscendingDescendingActionsHR ManagerHuman ResourcesReview Period2022-07-01 - 2022-12-302022-12-31ActivatedActivated')]</value>
      <webElementGuid>ccdcda15-cf40-4aa7-ba15-2f4b2fd01046</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
