<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_My Actions (9) Leave Requests to Approve (9) Timesheets to Approve(1) Pending Self Review</name>
   <tag></tag>
   <elementGuidId>15b5861b-e124-4cbd-881b-2b94710404b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div[2]/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f3e62027-76c3-49e3-8795-9f10b5481756</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oxd-grid-item oxd-grid-item--gutters orangehrm-dashboard-widget</value>
      <webElementGuid>2c1358fc-558c-4071-8909-c74fc582e077</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>My Actions (9) Leave Requests to Approve (9) Timesheets to Approve(1) Pending Self Review</value>
      <webElementGuid>a21fee7d-463e-4e1c-b54d-a82a2d8eed8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;oxd-layout&quot;]/div[@class=&quot;oxd-layout-container&quot;]/div[@class=&quot;oxd-layout-context&quot;]/div[@class=&quot;oxd-grid-3 orangehrm-dashboard-grid&quot;]/div[@class=&quot;oxd-grid-item oxd-grid-item--gutters orangehrm-dashboard-widget&quot;]</value>
      <webElementGuid>4df2b3c0-06c1-43a4-a02b-b1ac68ab960a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[2]/div/div[2]</value>
      <webElementGuid>34ed3cc3-e059-4b8d-9ec2-a4e9914d410a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]</value>
      <webElementGuid>b9c80c28-bd78-42a6-90e1-665113b781c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'My Actions (9) Leave Requests to Approve (9) Timesheets to Approve(1) Pending Self Review' or . = 'My Actions (9) Leave Requests to Approve (9) Timesheets to Approve(1) Pending Self Review')]</value>
      <webElementGuid>f0281b85-87da-47d9-a4d2-045a47e63dee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
