<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Expense TypeDateNoteAmount (Afghanistan Afghani)ActionsAccommodation2023-08-01Test600.00</name>
   <tag></tag>
   <elementGuidId>8b38bad5-b098-4d13-85b6-aab5a7f5c718</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.orangehrm-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div[2]/div/div/div[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e8a433b7-124b-4147-b1ca-4fde6251fa48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>orangehrm-container</value>
      <webElementGuid>4f899574-69b4-428c-8d85-6ca6617ce117</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Expense TypeDateNoteAmount (Afghanistan Afghani)ActionsAccommodation2023-08-01Test600.00</value>
      <webElementGuid>b8aa9205-7ee9-430e-8fef-dd624dfc05ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;oxd-layout&quot;]/div[@class=&quot;oxd-layout-container&quot;]/div[@class=&quot;oxd-layout-context&quot;]/div[@class=&quot;orangehrm-background-container&quot;]/div[@class=&quot;orangehrm-paper-container&quot;]/div[@class=&quot;orangehrm-container&quot;]</value>
      <webElementGuid>d513cbd6-9eb9-4134-a9e7-d581a4654ca7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[2]/div/div/div[4]</value>
      <webElementGuid>a0edf362-2928-4ef9-aadb-9107f76242da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]</value>
      <webElementGuid>2a44a765-8956-4d72-a632-455dc5e8d27e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Expense TypeDateNoteAmount (Afghanistan Afghani)ActionsAccommodation2023-08-01Test600.00' or . = 'Expense TypeDateNoteAmount (Afghanistan Afghani)ActionsAccommodation2023-08-01Test600.00')]</value>
      <webElementGuid>ebe4d66b-ae27-4cd9-a50a-5e6b4dc608c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
